notifications:
  email: false

dist: trusty

sudo: false

language: python

python:
  - '2.7'
  - '3.6'

install:
  - pip install -r requirements.txt

script:
  - make install

deploy:
  provider: pypi
  user: "lramage94"
  password:
    secure: T7ck1lb7E0GV12qR9PNbJkPZXKvK6shMGFrjhs/NOx1JuRdaCVNlTt4dvlf2cDS6kpWWpw4ZM2qk/z39Qljk4SZblVkpxIwTIsfAopKchsvlS8zWzcQc8Q/8ShKxafLbvrB2I1bX5l5LNPcbqqtvvFQjLnn61YVmT4f/qnFDF4LDpUwNgjImiUrma8atHtXbpxA2GgE3u/EoUsRuBl1prFLeLVqzdu0WeIk+9jlkyf9WzU5akHKKMwdcKNA7iIexIjYoRyrDNgRgtaX3jAKfqxVnExdAcQsShi61tfl0a6pFHnHUwx5Rs04CodYwU93uVFShoGC+7R2GsFNu9lGQCMlL44kd7B1q9S2jWI9P+AOF/bM/3DDK3tYhMGNM2iglwfhXqIdBTZnAfJjpPfSAchi0FzuATLEeOQXfddgmcIkdNBR4dU8IpIPKSvoPqqKjlE86B5jYr2Xux86D6bIl0YQgI9YzrI66RAn/ISyDxJCpK3OjX3aW/CPQ4lq6USrQOk/5Hs520qqCSpbtoip4J9D3+W4Nq66FX3omPSsaMCJlRt37Ay77EZrIwerwxVe/n/37RI2GYuPB+ZaYO1j/f10/4N2jisDx/bhKg0gwR41qJy8ONpL8pyQIBF6VxlGB1HfE7BAsleagacvGw8NOp+03aZ46lugnwVN3ECCvzxE=
  skip_cleanup: true
  on:
    tags: true
