site_name: Bootstrap/386 - MkDocs Theme
site_url: https://lramage.gitlab.io/mkdocs-bootstrap386

theme:
    name: bootstrap386

pages:
    - Home: index.md

plugins: []

repo_url: https://gitlab.com/lramage/mkdocs-bootstrap386
